services:
  dmi4er4-userbot:
    build: .
    platform: linux/amd64
    container_name: dmi4er4-userbot
    network_mode: host
    env_file:
      - .env.dmi4er4
    restart: unless-stopped

  taak-userbot:
    build: .
    platform: linux/amd64
    container_name: taak-userbot
    network_mode: host
    env_file:
      - .env.taak
    restart: unless-stopped
